import FHM.Bounds.RecursiveCountTransport

namespace FHM.Bounds.RecursiveCountTransportTests

open CountSubstitution ScopedScheme RecursiveContract RecursiveTyping RecursiveCountTransport

private def n : Count := .var ⟨.rigid, 7⟩
private def cap : Count := .var ⟨.rigid, 99⟩
private def schema : Scheme :=
  ⟨[7], [99], [⟨n, cap⟩], .arrow (.list n n (.prim .int)) (.list cap cap (.prim .int))⟩
private def simple : Scheme :=
  ⟨[7], [], [], .arrow (.list n n (.prim .int)) (.list n n (.prim .int))⟩
private def fixed : Declared :=
  { hm := .arrow (listTy (.prim .int)) (listTy (.prim .int))
    counts := simple
    wf := Scheme.wfBool_sound (by decide)
    shape := by simp [simple, Synth.BoundsTy.toTy, listTy, FHM.Bounds.listTyName]
    lc := (Ty.bvarsBelow_iff _).mp (by decide) }
private def symbolic : Instance simple [n] [7] where
  wf := fixed.wf
  arity := rfl
  finiteArgs := by
    intro a ha
    simp only [List.mem_singleton] at ha
    subst a
    exact .var
  argsScoped := by simp [Scope.CountScoped, n]
  capturesScoped := by simp [simple]
  bodyScoped := boundsScopedBool_sound (by decide)
  premisesScoped := by simp [simple]

private def loop : Expr := .lambda none (.app (.var 1) (.var 0))
private theorem symbolic_loop : Derives [7] [] [] [.recursive fixed] loop simple.body := by
  apply Derives.lambda (ann := none) True.intro
  apply Derives.app
  · exact .varRecursive (c := fixed) rfl symbolic (by intro σ _ g hg; simp [Instance.premises, fixed, simple] at hg)
  · exact .varMono rfl
  · exact SemanticSub.refl _ _

/-- Unlike the earlier direct universal group regression, this universal
    self-recursive RHS premise is GENERATED by transporting one symbolic proof. -/
private theorem every_loop_instance : ∀ args caller (inst : Instance simple args caller),
    Derives [7] ([7].zip args) inst.premises [.recursive fixed] loop (bounds ([7].zip args) simple.body) := by
  apply universal_rhs (s := simple) symbolic_loop
  · exact ⟨True.intro, True.intro⟩
  · intro γ hγ
    simp at hγ
  · intro c hc i hi
    simp only [List.mem_singleton, Binding.recursive.injEq] at hc
    subst c
    simp [fixed, simple] at hi

private def succeeds (r : Except String α) : Bool := match r with | .ok _ => true | _ => false
private def fails (r : Except String α) (needle : String) : Bool :=
  match r with | .error m => (m.splitOn needle).length > 1 | _ => false
private def lookupIsNone (rows : Bindings) (captures : List Nat) : Bool :=
  captures.all fun i => (lookup rows i).isNone

private def transportUse (args : List Count) (caller : List Nat) (outer : Bindings) (target : List Nat) :
    Except String (BoundsTy × List Constraint × List Count) := do
  let inst ← schema.instantiate args caller
  if hf : outer.all (fun row => row.2.noInf) = true then
    if hs : outer.all (fun row => countScopedBool target row.2) = true then
      if hk : lookupIsNone outer schema.captures = true then
        let mapped := instanceTransport inst outer
          (fun row hr => Count.noInf_of_isNoInf (List.all_eq_true.mp hf row hr)) target
          (fun row hr => countScopedBool_sound (List.all_eq_true.mp hs row hr))
          (by
            intro i hi
            have hn := List.all_eq_true.mp hk i hi
            cases hl : lookup outer i with
            | none => rfl
            | some c => simp [hl] at hn)
        pure (mapped.bounds, mapped.premises, args.map (count outer))
      else throw "test: outer interpretation changes a captured coordinate"
    else throw "test: replacement is outside target scope"
  else throw "test: nonfinite replacement"

private def selfRows : Bindings := [(7, .lit 3)]
private def symbolicRows : Bindings := [(7, .var ⟨.rigid, 42⟩)]
private def nestedRows : Bindings := [(42, .lit 4)]
private def cases : List (String × Bool) := [
  ("self-recursive telescope protected during caller count transport", match transportUse [n] [7, 99] selfRows [] with
    | .ok (.arrow (.list (.lit 3) (.lit 3) (.prim .int)) (.list lo hi (.prim .int)), _, args) =>
        lo == cap && hi == cap && args == [.lit 3]
    | _ => false),
  ("transport maps recursive requirements with caller arguments", match transportUse [n] [7, 99] selfRows [] with
    | .ok (_, premises, _) => premises == [⟨.lit 3, cap⟩]
    | _ => false),
  ("unselected caller count argument remains unchanged", match transportUse [.lit 4] [99] selfRows [] with
    | .ok (.arrow (.list (.lit 4) (.lit 4) _) _, _, args) => args == [.lit 4]
    | _ => false),
  ("caller coordinate distinct from callee telescope is transported", match
    transportUse [.var ⟨.rigid, 42⟩] [42, 99] nestedRows [] with
    | .ok (.arrow (.list (.lit 4) (.lit 4) _) _, _, args) => args == [.lit 4]
    | _ => false),
  ("symbolic replacement retains explicit target scope", succeeds
    (transportUse [n] [7, 99] symbolicRows [42])),
  ("symbolic replacement outside target scope rejected", fails
    (transportUse [n] [7, 99] symbolicRows []) "outside target scope"),
  ("captured coordinates cannot be rewritten by this bridge", fails
    (transportUse [n] [7, 99] [(99, .lit 3)] []) "captured coordinate"),
  ("infinite replacement cannot produce a recursive Nat use", fails
    (transportUse [n] [7, 99] [(7, .inf)] []) "nonfinite"),
  ("inferable replacement cannot enter caller count scope", fails
    (transportUse [n] [7, 99] [(7, .var ⟨.inferable, 42⟩)] [42]) "outside target scope"),
  ("caller argument arity remains checked before transport", fails
    (transportUse [] [99] selfRows []) "arity"),
  ("captured source scope remains checked before transport", fails
    (transportUse [n] [7] selfRows []) "capture"),
  ("simultaneous inserted argument is not recursively substituted", match
    transportUse [n] [7, 99] [(7, .var ⟨.rigid, 42⟩), (42, .lit 4)] [42] with
    | .ok (_, _, args) => args == [.var ⟨.rigid, 42⟩]
    | _ => false)]

example {s args caller Δ} (inst : Instance s args caller) (hu : inst.Usable Δ)
    (outer : Bindings) (hf : Finite outer) (target : List Nat)
    (hs : ∀ row ∈ outer, Scope.CountScoped target row.2)
    (hk : ∀ i ∈ s.captures, lookup outer i = none) :
    (instanceTransport inst outer hf target hs hk).Usable (Δ.map (constraint outer)) :=
  usable_transport inst hu outer hf target hs hk

example : ¬NoGroups (.letRec [none] [loop] loop) := fun h => h

def main : IO Unit := do
  for (name, ok) in cases do
    IO.println s!"{if ok then "PASS" else "FAIL"}: {name}"
    unless ok do throw (IO.userError s!"recursive count transport regression: {name}")

#eval main
#print axioms every_loop_instance

end FHM.Bounds.RecursiveCountTransportTests
